### ISSUE TITLE
serveStatic should allow omission of max-age from Cache-Control?

### ISSUE THREAD

**Issue by zyrolasting** [restify/plugins#104]
I want to serve all assets except `index.html` with a distant expiration so as to use cache-busting selectively. The problem with the below approach is that serveStatic imposes a conflicting `Cache-Control` header.

    server.pre((req, res, next) => {
        const path = url.parse(req.url);
        if (path.pathname === '/' && req.accepts('text/html')) {
            req.url = '/static/index.html';

            // Encourage the client to always download index.html.
            res.header('Expires', new Date(0));
            res.header('Cache-Control',
                'no-store, no-cache, must-revalidate');
        }

        next();
    });

    server.get(/\/static\/.*/, restify.serveStatic({
        directory: path.resolve('.'),
        maxAge: (10 * 365 * 24 * 60 * 60),
        gzip: true,
    }));

In this setup, my response has the following conflicting headers:

    Cache-Control:no-store, no-cache, must-revalidate, max-age=0
    Cache-Control:public, max-age=315360000

I try to make this more explicit by using the `file` option. But oddly enough, the below 404s requests to `index.html`. Probably my fault, but hell if I know why.

    server.pre((req, res, next) => {
        const path = url.parse(req.url);
        if (path.pathname === '/' && req.accepts('text/html')) {
            req.url = '/public/index.html';

            // Encourage the client to always download index.html.
            res.header('Expires', new Date(0));
            res.header('Cache-Control',
                'no-store, no-cache, must-revalidate');
        }

        next();
    });

    const directory = path.resolve('.');

    const serveDir = restify.serveStatic({
        directory,
        maxAge: (10 * 365 * 24 * 60 * 60),
        gzip: true
    });

    const serveIndex = restify.serveStatic({
        directory,
        file: 'index.html',
        maxAge: 0,
        gzip: false
    });

    server.get(/\/public\/.*/, function(req, res, next) {
        if (req.url === '/public/index.html') {
            serveIndex(req, res, next);
        } else {
            serveDir(req, res, next);
        }
    });

The point is that I am rewriting my code around serveStatic's inability to omit `max-age` (instead opting for a 3600 default), and I wonder why I should.  Is it possible to have `serveStatic` trust me to write my own headers, or is there a better way to go about this?

**Comment by retrohacker** [comment]
Hey @zyrolasting,

Thank you for opening this issue! We know serveStatic has quite a few short-comings. In fact, its almost easier at this point to just wire the `fs` module directly up to restify as opposed to trying to use this middleware. To answer your question, your approach looks pretty sane from a high level.

serveStatic has been a point of contention for a while. Dicussion is fragmented across a few different issues over at https://github.com/restify/node-restify

I believe the current plan is to eventually move serveStatic out into it's own module outside of the restify repo. The thought process is that restify is designed for building semantically correct, production ready, REST services designed for scale. Serving static content is outside of that wheelhouse. In addition, Node.js isn't the best at serving static content, you often get better mileage by fronting your restify service with NGinx for that use case. We know a lot of people are building webapps with restify, and that serving static content directly from Node.js simplifies that use case, so we are going to try to do this with care. If you would be interested in helping with that effort, or just want to chime in on the discussion, let us know :heart:

In the meantime, we are merging the plugins back into the core restify repo. Feel free to open an issue over there if you still have questions and I would be happy to help :smile:
