### ISSUE TITLE
Static file server loads files from cache as text/plain

### ISSUE THREAD

**Issue by jocull** [restify/plugins#11]
Happening on Firefox 43.0 for me today.

```
// This path points at the application root. The folder is called "docs"
const docPath = path.normalize(path.join(path.dirname(__filename), '../'))

// We then restrict access to only the documentation directory
server.get(/\/docs\//, restify.serveStatic({
    directory: docPath,
    default: 'index.html',
    // Cache sends everything as text/plain after first load.
    // I have no idea why. Setting maxAge to zero fixes, but never caches.
    // maxAge: 0,
}))
```

Can anyone reproduce? First load is all good, but next load everything is raw text and content-types are all messed up.

**Comment by micahr** [comment]
what version of restify / restify-plugins are you using?

**Comment by jocull** [comment]
Right now I have it declared as:

```
"restify": "^4.0.3"
```

**Comment by micahr** [comment]
Can you include the headers you get the first and second times?

**Comment by jocull** [comment]
First request:

![screenshot from 2016-01-05 10 07 31](https://cloud.githubusercontent.com/assets/246455/12119211/57e20380-b398-11e5-83f4-f31619a6f2e0.png)

Second request:

![screenshot from 2016-01-05 10 07 36](https://cloud.githubusercontent.com/assets/246455/12119210/5539c424-b398-11e5-860b-6768897ca79e.png)

**Comment by micahr** [comment]
Interesting. The issue seems to be with Firefox, as it doesn't make a second request to the server, instead it returns the cached html file.

**Comment by jocull** [comment]
I'm using Elementary OS right now, but this also happens in Midori (their
pre-package Chromeish browser). Not sure about other browsers.

**Comment by retrohacker** [comment]
Migrated to https://github.com/restify/node-restify
