### ISSUE TITLE
Add application/EDIFACT mime type

### ISSUE THREAD

**Issue by dawud-tan** [restify/plugins#55]
could we add application/EDIFACT mime type as defined in rfc 1767 to this file https://github.com/restify/plugins/blob/master/lib/plugins/bodyParser.js? afaik, there is one node library that already support this mime type, that is https://www.npmjs.com/package/edi

thanks

**Comment by DonutEspresso** [comment]
Hello, we would like to (in the future) open up the bodyParser and make it more customizable. For example, you could us a content-type and parser and we'll apply it for you. That way we don't have to continuously roll new types into the core plugin, which is currently a very small core set of a "standard" types. 

In the meantime, you should be able to use the package you referenced above to write your own body parser for the application/EDIFACT mime type. The raw body should be available on req.body.

**Comment by DonutEspresso** [comment]
I've logged #57 to capture the nature of this issue. I'm going to close this issue for now, please let us know if you have other questions.
