### ISSUE TITLE
Audit logger should include option to record current user

### ISSUE THREAD

**Issue by TonyFNZ** [restify/plugins#74]
The initiating user is an important part of any audit trail.  It is common practice to store the currently active user in `req.user`, however the [auditRequestSerializer](https://github.com/restify/plugins/blob/master/lib/plugins/audit.js#L56) does not include the user property, and cannot be externally overridden.

**Option A:**
Update the auditRequestSerializer to include `req.user`

**Option B:**
Update the auditLogger to allow the serializers to be overridden via `options` (with a fallback to the existing one as a default)

**Comment by DonutEspresso** [comment]
+1, I think being able to add additional fields for inclusion in the audit log would be very useful.

**Comment by retrohacker** [comment]
Migrated to: https://github.com/restify/node-restify/issues/1343
