### ISSUE TITLE
why does context plugin persist data across requests?

### ISSUE THREAD

**Issue by kamholz** [restify/plugins#82]
The documentation for the `pre.context` plugin states, "Provide req.set(key, val) and req.get(key) methods for setting and retrieving context to a specific request". But the [code](https://github.com/restify/plugins/blob/master/lib/pre/context.js#L16) in fact maintains the data structure over the lifetime of the app, not the request. Is this actually intentional? It resulted in some very unexpected behavior in my app. 

The very simple fix is to move `var data = {}` to the first line of the `context` function.

**Comment by DonutEspresso** [comment]
Thanks for the bug report! Sorry about that - v1.4.1 has been published to address this issue.
