### ISSUE TITLE
Test for 'metrics' not show existing bug

### ISSUE THREAD

**Issue by KostyaTretyak** [restify/plugins#86]
If we write this:

```js
console.log('****************************** before metrics.latency:', metrics.latency);
assert.isAtLeast(metrics.latency, 200);
console.log('****************************** after metrics.latency:', metrics.latency);
```

[here](https://github.com/restify/plugins/blob/9d9afd7a8c232390d35622818094cfbbb59cb44e/test/metrics.test.js#L133), and run test, we will see `before metrics.latency` but not `after metrics.latency`.

It seems that here bug in mocha and restify-plugins.

**Comment by KostyaTretyak** [comment]
Now I see this is not bug restify-plugin or mocha, but script is failed and test not show this.

**Comment by retrohacker** [comment]
Hey @KostyaTretyak,

Thank you for opening this issue. From my understanding it looks like you found this wasn't a bug in either the restify-plugin or mocha repos.

I'm going to close this for now as resolved. If I'm misunderstanding, please comment and I would be happy to re-open and discuss :heart:
